apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-04-17T17:54:04Z"
  labels:
    app: jupyter
  name: jupyter-svc
  namespace: jupyter-ns
  resourceVersion: "1369"
  uid: 11334318-5731-4bda-a25f-e7dd54c5df72
spec:
  clusterIP: 10.110.139.143
  clusterIPs:
  - 10.110.139.143
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30000
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: jupyter-pod
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
